general {
    ignore_dbus_inhibit = false
    before_sleep_cmd = sh -lc '$HOME/.config/hypr/scripts/hypr-screensaver.sh stop'
    after_sleep_cmd = sh -lc 'hyprctl dispatch dpms on'
}

listener {
    timeout = 180
    on-timeout = sh -lc '$HOME/.config/hypr/scripts/hypr-screensaver.sh random'
    on-resume = sh -lc '$HOME/.config/hypr/scripts/hypr-screensaver.sh stop-guarded 3'
}

listener {
    timeout = 600
    on-timeout = sh -lc '$HOME/.config/hypr/scripts/hypr-screensaver.sh stop; hyprctl dispatch dpms off'
    on-resume = sh -lc 'hyprctl dispatch dpms on'
}

listener {
    timeout = 3200
    on-timeout = sh -lc '$HOME/.config/hypr/scripts/hypr-screensaver.sh stop; systemctl suspend'
}
