group {
  groupbar {
    enabled = on
    height = 18
    font_size = 15
    font_family = Iosevka Bold
    text_padding = 6
    gradients = false

    # Explicit colors to avoid fallback to defaults.
    col.active = rgba(CE7688ff)
    col.inactive = rgba(5D333Cff)
    col.locked_active = rgba(BA6A7Bff)
    col.locked_inactive = rgba(49272Fff)
    text_color = rgba(FFDCB9ff)
  }
}
